metrics:  # NOT IMPLEMENTED YET
  - entropy
  - gini
  - hhi
  - nakamoto_coefficient

default_timeframe:
  start_date: 2020
  end_date: 2023

default_ledgers:
  - bitcoin
  - bitcoin_cash
  - dogecoin
  - ethereum  
  - litecoin  
  - tezos

db_directories:  # Paths to directories of snapshot db files; either absolute or relative from run.py; the first will be used to write newly created dbs
  - ./output
