metrics:  # NOT IMPLEMENTED YET
  - entropy
  - gini
  - hhi
  - nakamoto_coefficient

timeframe:
  start_year: 2010
  end_year: 2023

default_ledgers:
  - bitcoin
  - ethereum
  - dogecoin
  - litecoin
  - bitcoin_cash

db_directories:  # Paths to directories of snapshot db files; either absolute or relative from run.py; the first will be used to write newly created dbs
  - ./output
