metrics:
  - hhi
  - shannon entropy
  - gini
  - total entities
  - tau=0.33
  - tau=0.5
  - tau=0.66

default_timeframe:
  start_date: 2010
  end_date: 2023

default_ledgers:
  - bitcoin
  - bitcoin_cash
  - dogecoin
  - ethereum  
  - litecoin  
  - tezos

# Execution flags
force_map_addresses: false
force_map_balances: false
force_analyze: false
no_clustering: false

# The granularity for the analysis when two dates are provided in the --snapshot_dates argument (which are then interpreted as start and end dates). It can be one of: "day", "week", "month", "year", or empty. If empty, then only the snapshots for the given dates will be analyzed.
granularity: "month"

output_directories:  # Paths to directories of snapshot db files; either absolute or relative from run.py; the first will be used to write newly created dbs and the output of runs
  - ./output

input_directories:  # Paths to directories that contain raw input data
  - ./input
