# The metrics for which an analysis should be performed.
metrics:
  - hhi
  - shannon entropy
  - gini
  - total entities
  - tau=0.33
  - tau=0.5
  - tau=0.66
  - mpr

# The ledgers for which an analysis should be performed.
ledgers:
  - bitcoin
  - bitcoin_cash
  - dogecoin
  - ethereum  
  - litecoin  
  - tezos

# Execution flags
execution_flags:
  force_map_addresses: false
  force_map_balances: false
  force_analyze: false

# Analyze flags
analyze_flags:
  no_clustering: false
  top_limit_type: "absolute"  # one of two types: "absolute" or "percentage"; if absolute then value should be integer; if percentage then value should be float in [0, 1]
  top_limit_value: 0
  exclude_contract_addresses: false
  exclude_below_fees: false

# Plot flags
plot_parameters:
  plot: true
  ledgers:
    - bitcoin
    - bitcoin_cash
    - dogecoin
    - ethereum  
    - litecoin  
    - tezos
  metrics:
    - hhi
    - shannon entropy
    - gini
    - total entities
    - tau=0.33
    - tau=0.5
    - tau=0.66
    - mpr
  plot_line_params:
    # boolean to plot combinations of the other params
    # if true, then all possible combinations of all params are plotted
    # if false, then starting from a baseline where bools are false and top limits are 0, each other param is plotted sequencially while keeping the rest on the default
    combine_params: false  
    no_clustering:
      - true
      - false
    top_limit_absolute:
      - 0
      - 1000
      - 10000
    top_limit_percentage:
      - 0
      - 0.3
      - 0.5
    exclude_contract_addresses:
      - true
      - false

# The snapshots for which an analysis should be performed.
# Each snapshot is a string of the form YYYY-MM-DD.
# If granularity is also set, then the analysis will run on the timeframe of the two farthest snapshots.
snapshot_dates:
  - "2010"
  - "2023"

# The granularity for the analysis when two dates are provided in the --snapshot_dates argument (which are then interpreted as start and end dates). 
# It can be one of: "day", "week", "month", "year", or empty. If empty, then only the snapshots for the given dates will be analyzed.
granularity: "month"

# Paths to directories of snapshot db files; either absolute or relative from run.py.
# The first path will be used to write newly created dbs and the output of runs
output_directories:  
  - ./output

input_directories:  # Paths to directories that contain raw input data
  - ./input
